#!/bin/bash
# Autogenerated-style test: runs against the feature with default options.
set -e

source dev-container-features-test-lib

check "node is installed" node --version
check "npm is installed" npm --version
check "pnpm is installed" pnpm --version

reportResults
